---
- name: Install user
  hosts: all
  become: true

  tasks:
        - name: Add a new user named devops
          user:
                name: '{{ username }}'
                shell: /bin/bash

        - name: Add devops user to the sudoers
          copy:
                dest: "/etc/sudoers.d/devops"
                content: "devops  ALL=(ALL)  NOPASSWD: ALL"

        - name: Deploy SSH Key
          authorized_key: user={{ username }}
                          key="{{ lookup('file', '{{ user_key }}') }}"
                          state=present
